config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"

  get "/about",   to: "pages#about"
  get "/terms",   to: "pages#terms"
  get "/privacy", to: "pages#privacy"
  get "/contact", to: "pages#contact"

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  resources :tours, only: [:index] do
    collection do
      get :calendar, :import, :state, :contract, :customer
    end
  end

  resources :categories, only: [:show]
  resources :subcategories, only: [:show]

  resources :items do
    resources :records, except: [:edit, :update, :destroy]

    get :search, on: :collection
    member do
      get    :calendar
      post   :collect
      delete :uncollect
      patch  :open, :close
    end
  end

  resources :order, only: [] do
    resources :order_lenders, only: [:show]
  end

  resource :shopping_carts, only: [:show, :update]
  namespace :shopping_carts do
    resources :items, only:[] do
      member do
        post   :add
        delete :remove
      end
    end
  end

  resources :users, param: :account, only: [:show, :edit, :update] do
    member do
      get    :reviews, :lender_reviews, :borrower_reviews, :items
      put    :follow
      patch  :avatar, :save
      delete :unfollow
    end

    resources :subcategories, only: [] do
      resources :vectors, only: [:index]
    end
  end

  resources :attachments, only: [:destroy] do
    get :download, on: :member
  end

  resources :notifications, only: [:index, :show] do
    put :mark_as_read, on: :member
  end

  namespace :account do
    resource :settings, only: [:show, :update] do
      get   :preferences, :phone_confirmation, :lender, :become
      post  :phone_confirmed, :upload
      patch :save
    end

    resources :categories, only: [:index]
    resources :subcategories, only: [:index] do
      resources :vectors, only: [:create, :destroy, :index]
    end
    resources :vectors, only: [] do
      resources :selections, only: [:create, :destroy]
    end

    resources :customers, except: [:destroy] do
      resources :items, only: [:index]
      resource :shopping_carts, only: [:show, :update]

      scope module: :shopping_carts do
        resources :items, only:[] do
          member do
            post   :add
            delete :remove
          end
        end
      end
    end
  end

  namespace :lender do
    resources :items, only: [:index, :show] do
      collection do
        get  :wish, :importer
        post :import
      end
    end

    resources :orders, only: [:index, :show] do
      resources :order_lenders, only: [] do
        member do
          put :delivering, :renting, :returning
        end
      end

      get :calendar, on: :collection
    end
  end

  namespace :borrower do
    resources :orders, only: [:index, :show] do
      resources :order_lenders, only: [] do
        member do
          put    :remitting
          delete :withdrawing
        end
      end

      get :calendar, on: :collection
    end
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  include BookedDates

  attr_accessor :started_at, :ended_at

  validates_presence_of :started_at, :ended_at, unless: :new_record?
  validate :shopping_cart_items_valid?

  belongs_to :user, polymorphic: true

  has_many :shopping_cart_items
  accepts_nested_attributes_for :shopping_cart_items

  has_many :items, through: :shopping_cart_items
  has_many :records, through: :items
  has_many :lenders, ->{uniq}, through: :items

  def add(item)
    unless item_for(item)
      shopping_cart_items.create(
        item_id: item.id,
        price: item.price,
        deliver_fee: item.deliver_fee,
        free_days: item.lender.free_days,
        deposit: item.deposit,
        period: item.period
      )
    end
  end

  def remove(item)
    cart_item = item_for(item)
    return unless cart_item
    cart_item.delete
  end

  def item_for(item)
    shopping_cart_items.where(item_id: item.id).first
  end

  def empty?
    shopping_cart_items.empty?
  end

  def clear
    shopping_cart_items.delete_all
  end

  def shopping_cart_lender_items
    shopping_cart_items.group_by(&:lender)
  end

  def checkout
    order_price, order_deposit, order_deliver_fee = 0, 0, 0

    order = user.orders.create(started_at: started_at, ended_at: ended_at)

    shopping_cart_lender_items.each do |lender, shopping_cart_items|
      lender_price, lender_deposit, lender_deliver_fee = 0, 0, 0

      order_lender = order.order_lenders.create!(
        lender: lender,
        deliver: shopping_cart_items.first.deliver
      )

      shopping_cart_items.each do |shopping_cart_item|
        record_params = shopping_cart_item_record_params(shopping_cart_item)
        record = shopping_cart_item.item.records.build(record_params)
        record.attributes = { order: order, order_lender: order_lender }
        record.save

        # 業者此份訂單總金額計算
        lender_price       += record.price
        lender_deposit     += record.item_deposit
        lender_deliver_fee += record.deliver_fee if record.delivery_needed?
      end

      # 紀錄業者訂單金額
      order_lender.update(
        price:       lender_price,
        deposit:     lender_deposit,
        deliver_fee: lender_deliver_fee
      )

      # 訂單總金額計算
      order_price       += lender_price
      order_deposit     += lender_deposit
      order_deliver_fee += lender_deliver_fee
    end
    clear

    # 紀錄訂單總金額
    order.update(
      price:       order_price,
      deposit:     order_deposit,
      deliver_fee: order_deliver_fee
    )
    order
  end

  def lender_request_borrower_info_needed?
    lenders.each {|lender| return true if lender.borrower_info_provide}
    return false
  end

  private
    def shopping_cart_items_valid?
      shopping_cart_items.each_with_index do |shopping_cart_item, index|
        shopping_cart_item.valid?
        record_params = shopping_cart_item_record_params(shopping_cart_item)
        record = shopping_cart_item.item.records.build(record_params)

        unless record.valid?
          errors.add(:shopping_cart_items,
                     :'record.overlaped',
                     index: (index + 1),
                     msg: record.errors.values.join('，')
          )
        end
      end
    end

    def shopping_cart_item_record_params(shopping_cart_item)
      {
        started_at: started_at,
        ended_at: ended_at,
        borrower: user,
        item_price: shopping_cart_item.price,
        deliver_id: shopping_cart_item.deliver_id,
        deliver_fee: shopping_cart_item.deliver_fee,
        item_deposit: shopping_cart_item.deposit,
        free_days: shopping_cart_item.free_days,
        item_period: shopping_cart_item.period,
        send_period: shopping_cart_item.send_period
      }
    end
end

app/controllers/account/shopping_carts/items_controller.rb
class Account::ShoppingCarts::ItemsController < ApplicationController
  before_action :login_required
  load_and_authorize_resource :customer, through: :current_user
  load_and_authorize_resource :item, through: :current_user
  skip_authorize_resource :item
  before_action :load_customer_shopping_cart

  def add
    @shopping_cart.add @item
  end

  def remove
    @shopping_cart.remove @item
    redirect_to :back
  end
end

app/controllers/account/shopping_carts_controller.rb
class Account::ShoppingCartsController < ApplicationController
  before_action :login_required
  load_and_authorize_resource :customer, through: :current_user
  before_action :load_customer_shopping_cart
  before_action :validates_borrower_info
  before_action :load_disabled_dates
  before_action ->{ set_title_meta_tag prefix: @customer.logo_name }

  def show
    @lender_shopping_cart_items = @shopping_cart.shopping_cart_items
                                                .includes(:deliver, :lender, item: :delivers)
                                                .group_by(&:lender)
  end

  def update
    if @shopping_cart.update(shopping_cart_params)
      order = @shopping_cart.checkout
      redirect_to lender_order_path(order)
    else
      validates_borrower_info { return }
      @lender_shopping_cart_items = @shopping_cart.shopping_cart_items.group_by(&:lender)
      render :show
    end
  end

  private
    def shopping_cart_params
      params.require(:shopping_cart).permit(
        :started_at, :ended_at,
        shopping_cart_items_attributes: [:id, :deliver_id, :send_period]
      ).deep_symbolize_keys
    end

    def load_disabled_dates
      @disabled_dates = @shopping_cart.booked_dates
    end

    def validates_borrower_info
      if borrower_info_needed?
        errors = @customer.profile.validates_detail_info
        unless errors.empty?
          redirect_to(
            edit_account_customer_path(@customer, redirect_url: account_customer_shopping_carts_path(@customer)),
            alert: t('activerecord.errors.models.profile.attributes.info.blank', attrs: errors.join('、'))
          ) and yield
        end
      end
    end

    def borrower_info_needed?
      return true if current_user.borrower_info_provide
      @shopping_cart.shopping_cart_items.each do |shopping_cart_item|
        return true if shopping_cart_item.deliver.present? and shopping_cart_item.deliver.address_needed?
      end
      return false
    end
end

app/controllers/shopping_carts/items_controller.rb
class ShoppingCarts::ItemsController < ApplicationController
  before_action :login_required
  before_action :load_shopping_cart
  load_and_authorize_resource

  # post items/:id/add
  def add
    @shopping_cart.add @item
  end

  # delete items/:id/remove
  def remove
    @shopping_cart.remove @item
    redirect_to :back
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :login_required
  before_action :load_shopping_cart
  before_action -> { validates_borrower_info { return } }
  before_action :load_disabled_dates
  before_action :set_title_meta_tag

  def show
    @lender_shopping_cart_items = @shopping_cart.shopping_cart_items
                                                .includes(:deliver, :lender, item: :delivers)
                                                .group_by(&:lender)
  end

  def update
    @shopping_cart.user = current_user
    if @shopping_cart.update(shopping_cart_params)
      order = @shopping_cart.checkout

      order.order_lenders.includes(:lender, :records).each do |order_lender|
        OrderLenderMailer.send_payment_message(order_lender).deliver_now

        order_lender.lender.notify(
          t('controller.shopping_carts.update.notify_lender',
            name:   current_user.logo_name,
            period: view_context.render_datetime_period(order),
            count:  order_lender.records.count),
          lender_order_url(order)
        )
      end
      redirect_to borrower_order_path(order)
    else
      validates_borrower_info { return }
      @lender_shopping_cart_items = @shopping_cart.shopping_cart_items.group_by(&:lender)
      render :show
    end
  end

  private
    def shopping_cart_params
      params.require(:shopping_cart).permit(
        :started_at, :ended_at,
        shopping_cart_items_attributes: [:id, :deliver_id, :send_period]
      ).deep_symbolize_keys
    end

    def load_disabled_dates
      @disabled_dates = @shopping_cart.booked_dates
    end

    def validates_borrower_info
      if borrower_info_needed?
        errors = current_user.profile.validates_detail_info
        unless errors.empty?
          redirect_to(
            edit_user_path(current_user, redirect_url: shopping_carts_path),
            alert: t('activerecord.errors.models.profile.attributes.info.blank', attrs: errors.join('、'))
          ) and yield
        end
      end
    end

    def borrower_info_needed?
      return true if @shopping_cart.lender_request_borrower_info_needed?
      @shopping_cart.shopping_cart_items.each do |shopping_cart_item|
        return true if shopping_cart_item.deliver.present? and shopping_cart_item.deliver.address_needed?
      end
      return false
    end
end

app/helpers/account/shopping_carts/items_helper.rb
module Account::ShoppingCarts::ItemsHelper
end

app/helpers/account/shopping_carts_helper.rb
module Account::ShoppingCartsHelper
end

app/helpers/shopping_carts/items_helper.rb
module ShoppingCarts::ItemsHelper
  def render_add_shopping_carts_item_link(item, customer = nil)
    add_url = (customer) ?
      add_account_customer_item_path(customer, item) : add_shopping_carts_item_path(item)

    link_to render_icon('plus', class: 'text-danger'),
            add_url,
            class: 'btn btn-default', method: :post, remote: true,
            title: t('controller.items.action.add'), data: {toggle: 'tooltip'}
  end

  def render_remove_shopping_carts_item_link(item, customer = nil)
    remove_url = (customer) ?
      remove_account_customer_item_path(customer, item) : remove_shopping_carts_item_path(item)

    link_to render_icon('trash'),
            remove_url,
            class: 'btn btn-default', method: :delete,
            title: t('controller.items.action.remove'), data: {toggle: 'tooltip'}
  end

  def render_operate_shopping_carts_item_links(item, customer = nil)
    links = raw [
      render_add_shopping_carts_item_link(item, customer),
      render_remove_shopping_carts_item_link(item, customer)
    ].join
    content_tag :div, links, class: 'btn-group'
  end
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
  def render_shopping_cart_link
    icon = render_icon('shopping-cart',
                       title: t('controller.name.shopping_carts'),
                       data: {toggle: 'tooltip', placement: 'bottom'})
    link_to(icon, shopping_carts_path, class: 'icon-navbar')
  end

  def render_shopping_cart_form_url(customer = nil)
    if customer
      account_customer_shopping_carts_path(customer)
    else
      shopping_carts_path
    end
  end
end

app/views/shopping_carts/_form.html.slim
h1.text-center = t('controller.shopping_carts.action.show')

= render_default_content(shopping_cart.items) do
  - items_link_path = customer ? account_customer_items_path(customer) : search_items_path
  = t('helpers.shopping_carts.empty')
  mark = link_to(t('helpers.shopping_carts.go_rent'), items_link_path, class: 'text-danger')

- unless shopping_cart.empty?
  .item_record_order
    = simple_form_for shopping_cart, url: render_shopping_cart_form_url(customer) do |f|
      = f.input :started_at, as: :date_time_picker, input_html: {id: 'record_started_at'}
      = f.input :ended_at, as: :date_time_picker, input_html: {id: 'record_ended_at'}

      .shopping_cart
        - if shopping_cart.errors.present?
          .text-center
            - shopping_cart.errors.get(:shopping_cart_items).each do |msg|
              p: code = msg

        - @lender_shopping_cart_items.each do |lender, shopping_cart_items|
          .panel.panel-primary.lender
            .panel-heading
              .panel-title = lender.logo_name
            table.table.table-condensed
              thead
                tr
                  th.col-xs-6 = t('simple_form.labels.shopping_cart_item.name')
                  th.col-xs-2 = t('simple_form.labels.shopping_cart_item.price')
                  th.col-xs-1 = t('simple_form.labels.shopping_cart_item.deposit')
                  th.col-xs-1 = t('simple_form.labels.shopping_cart_item.deliver_fee')
                  th.col-xs-1 = t('helpers.shopping_carts.subtotal_price')
                  th.col-xs-1
              tbody
                = render partial: 'shopping_carts/shopping_cart_item',
                         collection: shopping_cart_items,
                         locals:{f: f, customer: customer}
            .panel-footer
              = f.simple_fields_for :shopping_cart_items, shopping_cart_items.first do |cart_item|
                = cart_item.input :deliver_id,
                                  as: :select,
                                  collection: cart_item.object.item.select_delivers,
                                  input_html:{class: 'lender_deliver form-control'},
                                  include_blank: t('helpers.select.deliver_blank'),
                                  label: t('simple_form.labels.shopping_cart_item.deliver_id')
                .send_period_container
                  = cart_item.input :send_period,
                                    as: :radio_buttons,
                                    item_wrapper_class: 'inline',
                                    input_html: {class: 'lender_send_period'},
                                    wrapper_html: {class: 'clearfix'},
                                    label: t('simple_form.labels.shopping_cart_item.send_period')

        .row
          .col-xs-12
            .col-xs-offset-4.col-xs-2.text-right = t('helpers.shopping_carts.rent_days')
            #rent_days.col-xs-1
            .col-xs-offset-1.col-xs-2.text-right = t('helpers.shopping_carts.total_price')
            #total_price.col-xs-1
            .col-xs-1
              = f.button :submit,
                         t('helpers.submit.submit'),
                         class: 'btn btn-success btn-sm',
                         data: {disable_with: t('helpers.submit.wait')}

  javascript:
    $(document).ready(function(){
      update_rent_days_price();
      buildDateTimePicker($('.form_datetime'), 'YYYY-MM-DD', #{raw disabled_dates});
      rentRecordPickerChange();
    });

app/views/shopping_carts/_shopping_cart_item.html.slim
- item = shopping_cart_item.item

tr.item_record
  = hidden_field_tag :item_price, shopping_cart_item.price, class: 'item_price', id: nil
  = hidden_field_tag :free_days, shopping_cart_item.free_days, class: 'free_days', id: nil
  = hidden_field_tag :item_deposit, shopping_cart_item.deposit, class: 'item_deposit', id: nil
  = hidden_field_tag :item_period, shopping_cart_item.period, class: 'item_period', id: nil

  td
    div = link_to item.name, item_path(item)
    - if shopping_cart_item.per_day?
      .label.label-default = t('helpers.records.form.free_days', days: shopping_cart_item.free_days)
  td = render_item_obj_price_period shopping_cart_item
  td = render_currency_money shopping_cart_item.deposit
  td
    span.item_deliver_fee
    .hide
      = f.simple_fields_for :shopping_cart_items, shopping_cart_item do |cart_item|
        = cart_item.input :deliver_id,
                           as: :select,
                           collection: cart_item.object.item.select_delivers,
                           label: false,
                           wrapper: :default,
                           input_html:{class: 'item_deliver form-control'},
                           include_blank: t('helpers.select.deliver_blank')
        = cart_item.input :send_period, as: :radio_buttons, input_html: {class: 'send_period'}
  td.item_subtotal
  td = render_remove_shopping_carts_item_link(item, customer)

app/views/shopping_carts/show.html.slim
/customer 用來判斷為 account/shopping_cart or shopping_carts
= render partial: 'shopping_carts/form',
         locals: {shopping_cart: @shopping_cart, shopping_cart_items: @shopping_cart_items,
                  disabled_dates: @disabled_dates, customer: nil}